export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST'
export const DELETE_ITEM_ON_LIST = 'DELETE_ITEM_ON_LIST'
export const ADD_ITEM_TO_TODO_LIST = 'ADD_ITEM_TO_TODO_LIST'
export const DELETE_ITEM_ON_TODO_LIST = 'DELETE_ITEM_ON_TODO_LIST'
